// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttkmsbntdidjvnivgnlk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0a21zYm50ZGlkanZuaXZnbmxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NTgyNDcsImV4cCI6MjA3MTQzNDI0N30.qyLaNJVPPlySJXMQFWeYxGTQ23e-Z9oR9L4RmnCEPfs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});